[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/YOUR_INFURA_KEY"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"

[etherscan]
sepolia = { key = "YOUR_ETHERSCAN_KEY" }
bsc_testnet = { key = "YOUR_BSCSCAN_KEY" } 