[package]
name = "minimal-escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "23.0.0"

[dev_dependencies]
soroban-sdk = { version = "23.0.0", features = ["testutils"] }

[profile.release-with-logs]
inherits = "release"
debug-assertions = true 